
export const CRICKET_PLAYERS = [
  { id: 1, name: 'Virat Kohli', role: 'Batsman', country: 'India' },
  { id: 2, name: 'Rohit Sharma', role: 'Batsman', country: 'India' },
  { id: 3, name: 'MS Dhoni', role: 'Wicket-keeper', country: 'India' },
  { id: 4, name: 'Jasprit Bumrah', role: 'Bowler', country: 'India' },
  { id: 5, name: 'Hardik Pandya', role: 'All-rounder', country: 'India' },
  { id: 6, name: 'KL Rahul', role: 'Batsman', country: 'India' },
  { id: 7, name: 'Ravindra Jadeja', role: 'All-rounder', country: 'India' },
  { id: 8, name: 'Mohammed Shami', role: 'Bowler', country: 'India' },
  { id: 9, name: 'Rishabh Pant', role: 'Wicket-keeper', country: 'India' },
  { id: 10, name: 'Shubman Gill', role: 'Batsman', country: 'India' },
  { id: 11, name: 'Babar Azam', role: 'Batsman', country: 'Pakistan' },
  { id: 12, name: 'Kane Williamson', role: 'Batsman', country: 'New Zealand' },
  { id: 13, name: 'Steve Smith', role: 'Batsman', country: 'Australia' },
  { id: 14, name: 'Jos Buttler', role: 'Wicket-keeper', country: 'England' },
  { id: 15, name: 'Ben Stokes', role: 'All-rounder', country: 'England' },
  { id: 16, name: 'Pat Cummins', role: 'Bowler', country: 'Australia' },
  { id: 17, name: 'Trent Boult', role: 'Bowler', country: 'New Zealand' },
  { id: 18, name: 'David Warner', role: 'Batsman', country: 'Australia' },
  { id: 19, name: 'AB de Villiers', role: 'Batsman', country: 'South Africa' },
  { id: 20, name: 'Kagiso Rabada', role: 'Bowler', country: 'South Africa' },
  { id: 21, name: 'Quinton de Kock', role: 'Wicket-keeper', country: 'South Africa' },
  { id: 22, name: 'Rashid Khan', role: 'Bowler', country: 'Afghanistan' },
  { id: 23, name: 'Glenn Maxwell', role: 'All-rounder', country: 'Australia' },
  { id: 24, name: 'Jonny Bairstow', role: 'Wicket-keeper', country: 'England' },
  { id: 25, name: 'Mitchell Starc', role: 'Bowler', country: 'Australia' },
  { id: 26, name: 'Shakib Al Hasan', role: 'All-rounder', country: 'Bangladesh' },
  { id: 27, name: 'Joe Root', role: 'Batsman', country: 'England' },
  { id: 28, name: 'Eoin Morgan', role: 'Batsman', country: 'England' },
  { id: 29, name: 'Faf du Plessis', role: 'Batsman', country: 'South Africa' },
  { id: 30, name: 'Mohammed Siraj', role: 'Bowler', country: 'India' }
];
